/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ian678_ocrad_Ocrad */

#ifndef _Included_com_ian678_ocrad_Ocrad
#define _Included_com_ian678_ocrad_Ocrad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1version
  (JNIEnv *, jobject);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1open
  (JNIEnv *, jobject);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_get_errno
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1get_1errno
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_set_image
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1set_1image
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_set_image_from_file
 * Signature: (JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1set_1image_1from_1file
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_set_utf8_format
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1set_1utf8_1format
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_set_threshold
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1set_1threshold
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_scale
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1scale
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_recognize
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1recognize
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_result_blocks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1result_1blocks
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_result_lines
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1result_1lines
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_result_chars_total
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1result_1chars_1total
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_result_chars_block
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1result_1chars_1block
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_result_chars_line
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1result_1chars_1line
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_result_line
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1result_1line
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_ian678_ocrad_Ocrad
 * Method:    OCRAD_result_first_character
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ian678_ocrad_Ocrad_OCRAD_1result_1first_1character
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
