name: Check formatting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:19.10

    steps:
    - uses: actions/checkout@v2
    - name: apt-get update
      run: apt-get update

    - name: Install clang-format
      run: apt-get -y install clang-format

    - name: Check formatting
      run: |
        chmod +x ./tools/check-format.sh
        ./tools/check-format.sh
